config/routes.rb
Acompishm::Application.routes.draw do
  resources :achievements

	root :to => "page#home"

	devise_for :users, :controllers => { :registrations => 'registrations' }
	
	match "userhome" => "page#userhome", :as => "userhome"
	match '/auth/:provider/callback' => 'authentications#create'

	resources :authentications
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
	def given_to
		if self.user_id
			User.find_by_id(self.user_id)
		else
			User.new
		end
	end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  
  Providers = %w[facebook open_id twitter]
  
  def provider_name
  	if provider == 'open_id'
  		"OpenID"
  	else
	  	provider.titleize
	end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :username
  
	validates_presence_of :username
  
	has_many :authentications
  
	def apply_omniauth(omniauth)
		self.email = omniauth['user_info']['email'] if email.blank?
		authentications.build(:provider => omniauth["provider"], :uid => omniauth["uid"])
	end

	def password_required?
		(authentications.empty? || !password.blank?) && super
	end
	
	def providers
		p = []
		authentications.map { |auth| p.push auth.provider } 
		p
	end
	
	def achievements
		Achivement.find_by_user_id(self.id)
	end
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
	def index
		@achievements = Achievement.all
	end
  
	def show
		@achievement = Achievement.find(params[:id])
	end
  
	def new
		@achievement = Achievement.new
	end
  
	def create
		@achievement = Achievement.new(params[:achievement])
		if @achievement.save
			flash[:notice] = "Successfully created achievement."
			redirect_to @achievement
		else
			render :action => 'new'
		end
	end
  
	def edit
		@achievement = Achievement.find(params[:id])
	end
  
	def update
		@achievement = Achievement.find(params[:id])
		if @achievement.update_attributes(params[:achievement])
			flash[:notice] = "Successfully updated achievement."
			redirect_to @achievement
		else
			render :action => 'edit'
		end
	end
  
	def destroy
		@achievement = Achievement.find(params[:id])
		@achievement.destroy
		flash[:notice] = "Successfully destroyed achievement."
		redirect_to achievements_url
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	
	private
	
	def after_sign_in_path_for(resource_or_scope)
		userhome_path
	end  
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
	@authentications = current_user.authentications if current_user
  end
  
  def create
	omniauth=request.env["omniauth.auth"]
	authentication = Authentication.find_by_provider_and_uid(omniauth["provider"], omniauth["uid"])
	if authentication
		flash[:notice] = "Logged in using #{omniauth["provider"].titleize}"
		sign_in_and_redirect(:user, authentication.user)	
	elsif current_user
		current_user.authentications.create!(:provider => omniauth["provider"], :uid => omniauth["uid"])
		flash[:notice] = "Account Linked"
		redirect_to userhome_path
	else
		user = User.new
		user.apply_omniauth(omniauth)
		if user.save
			flash[:notice] = "Created Account with #{omniauth["provider"].titleize}"
			sign_in_and_redirect(:user, authentication.user)
		else
			session[:omniauth] = omniauth.except('extra')
			redirect_to new_user_registration_path
		end
	end
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def home
	end
	
	def userhome
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	def create
		super
		session[:omniauth] = nil unless @user.new_record?
	end

	private
	
	def build_resource(*args)
		super
		if session[:omniauth]
			@user.apply_omniauth(session[:omniauth])
			@user.valid?
		end
	end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(s)
		content_for(:title) { s }
	end
	
	def path_to_home
		if current_user
			userhome_path
		else
			root_path
		end
	end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/achievements/_form.html.erb
<%= form_for @achievement do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/achievements/edit.html.erb
<% title "Edit Achievement" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @achievement %> |
  <%= link_to "View All", achievements_path %>
</p>

app/views/achievements/index.html.erb
<% title "Achievements" %>

<div id="main_pane">
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>User</th>
  </tr>
  <% for achievement in @achievements %>
    <tr>
      <td><%= achievement.name %></td>
      <td><%= achievement.description %></td>
      <td><%= achievement.user_id %></td>
      <td><%= link_to "Show", achievement %></td>
      <td><%= link_to "Edit", edit_achievement_path(achievement) %></td>
      <td><%= link_to "Destroy", achievement, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Achievement", new_achievement_path %></p>
</div>

app/views/achievements/new.html.erb
<% title "New Achievement" %>

<%= render 'form' %>

<p><%= link_to "Back to List", achievements_path %></p>

app/views/achievements/show.html.erb
<% title "Achievement" %>

<p>
  <strong>Name:</strong>
  <%= @achievement.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @achievement.description %>
</p>
<p>
  <strong>User:</strong>
  <%= @achievement.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_achievement_path(@achievement) %> |
  <%= link_to "Destroy", @achievement, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", achievements_path %>
</p>

app/views/authentications/index.html.erb
<% title "Authentications" %>

<h1>Authenticate</h1>

<% if current_user %>
	It is possible to use multiple authentication providers with your account. Simply click on the Provider you want to add below:<br />
<% else %>
	<b>You can use any of the services below to login:</b><br />
<% end %>
<div id="buttons">
<% Authentication::Providers.each do |provider| %>
	<div class="authbutton">
	<% if current_user %>
		<% unless current_user.providers.include? provider %>
			<%= link_to image_tag("authbuttons/png/#{provider.gsub(/_/,'')}_64.png"), "/auth/#{provider}" %><br /><%= provider.gsub(/_/,'').titleize %>
		<% else %>
			<%= image_tag("authbuttons/png/#{provider.gsub(/_/,'')}_32.png") %><br /><%= provider.gsub(/_/,'').titleize %><br /><%= current_user.authentications.find_by_provider(provider).uid %>
		<% end %>
	<% else %>
		<%= link_to image_tag("authbuttons/png/#{provider.gsub(/_/,'')}_64.png"), "/auth/#{provider}" %><br /><%= provider.gsub(/_/,'').titleize %>
	<% end %>
	</div>
<% end %>
</div>
<% unless current_user %>
	You don't have to use a third party service to authenticate, you can use a good old username and password by either <%= link_to "Signing In", new_user_session_path %> or <%= link_to "Sigining Up", new_user_registration_path %>.
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Acompishm</title>
	<%= csrf_meta_tag %>
	<%= stylesheet_link_tag 'main' %>
</head>
<body>
<div id="topbar"><%= link_to "Acompishm", path_to_home %>
<% if current_user %>
	<span id="user"><% current_user.authentications.each do |auth| %>
		<%= image_tag "authbuttons/png/#{auth.provider.gsub(/_/,'')}_32.png", :width => 16, :height => 16 %>
	<% end %><%= current_user.username %> - <%= link_to 'Logout', destroy_user_session_path %></span>
<% end %>
</div>
<% if notice %>
<div id="notice"><%= notice %></div>
<% end %>

<div id="container"><%= yield %></div>

</body>
</html>

app/views/page/home.html.erb
<%= render 'shared/infobox' %>

<div class="homebox"><h2><%= link_to 'Sign In', authentications_path %></h2>You can Sign In with:<br />
<% Authentication::Providers.each do |provider| %>
	<div class="authbutton">
	<%= link_to image_tag("authbuttons/png/#{provider.gsub(/_/,'')}_64.png"), "/auth/#{provider}" %><br /><%= provider.gsub(/_/,'').titleize %>
	</div>
<% end %>
</div>

<div class="homebox"><h2>Another Box</h2>MOAR</div>

app/views/page/userhome.html.erb
<h1>Welcome Back!</h1>

<%= render 'shared/infobox' %>

<div class="homebox"><h2><%= current_user.username %></h2>
Linked Accounts:<br />
<% current_user.authentications.each do |auth| %>
	<div id="in-use-auth"><%= image_tag "authbuttons/png/#{auth.provider.gsub(/_/,'')}_32.png" %><strong><%= auth.provider_name %></strong><br /><%= auth.uid %></div>
<% end %>

<%= link_to "Add More", authentications_path %><br />
<%= link_to 'Logout', destroy_user_session_path %></div>

app/views/shared/_infobox.html.erb
<div class="homebox"><h2>Welcome to Acompishm</h2>Social Achivements for all.<br />
<br />
STATUS</div>